/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.badillosoft.server;

import com.badillosoft.FileUI;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 * La clase FileServerUI muestra una ventana que permite ajustar 4 archivos
 * A, B, C y D para transmitir los archivos ajustados. Solo procesa a un cliente
 * a la vez.
 * 
 * @author Alan Badillo Salas [badillo.soft@hotmail.com]
 * @version 1.0
 * @see com.badillosoft.server.FileServer
 */
public class FileServerUI extends javax.swing.JFrame {

    /**
     * Creates new form FileServerUI
     */
    public FileServerUI() {
        initComponents();
        
        // Ajustamos el comportamiento de la barra de progreso A para que
        // al actualizarse ajuste un texto con el porcentaje de la barra
        this.jProgressBarA.addChangeListener((evt) -> {
            // Ajustamos el label State (el de abajo) con el porcentaje de la barra de progreso
            this.jLabelState.setText(String.format("A: %d%%", this.jProgressBarA.getValue()));
            // Si el progreso es 0 mostramos el mensaje "Listo"
            if (this.jProgressBarA.getValue() == 0) {
                this.jLabelState.setText("Listo");
            }
        });
        
        this.jProgressBarB.addChangeListener((evt) -> {
            this.jLabelState.setText(String.format("B: %d%%", this.jProgressBarB.getValue()));
            if (this.jProgressBarB.getValue() == 0) {
                this.jLabelState.setText("Listo");
            }
        });
        
        // TODO: en base al jProgressBarA y jProgressBarB completa
        // el código para C y D
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldA = new javax.swing.JTextField();
        jButtonA = new javax.swing.JButton();
        jLabelA = new javax.swing.JLabel();
        jLabelB = new javax.swing.JLabel();
        jTextFieldB = new javax.swing.JTextField();
        jButtonB = new javax.swing.JButton();
        jLabelC = new javax.swing.JLabel();
        jTextFieldC = new javax.swing.JTextField();
        jButtonC = new javax.swing.JButton();
        jLabelD = new javax.swing.JLabel();
        jTextFieldD = new javax.swing.JTextField();
        jButtonD = new javax.swing.JButton();
        jLabelState = new javax.swing.JLabel();
        jProgressBarA = new javax.swing.JProgressBar();
        jProgressBarB = new javax.swing.JProgressBar();
        jProgressBarC = new javax.swing.JProgressBar();
        jProgressBarD = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BadilloSoft - File Server");

        jTextFieldA.setEnabled(false);

        jButtonA.setText("...");

        jLabelA.setText("Path A");

        jLabelB.setText("Path B");

        jTextFieldB.setEnabled(false);

        jButtonB.setText("...");

        jLabelC.setText("Path C");

        jTextFieldC.setEnabled(false);

        jButtonC.setText("...");

        jLabelD.setText("Path D");

        jTextFieldD.setEnabled(false);

        jButtonD.setText("...");

        jLabelState.setText("Listo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jTextFieldD, javax.swing.GroupLayout.DEFAULT_SIZE, 398, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonD))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelA)
                            .addComponent(jLabelD))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jProgressBarD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelB)
                                    .addComponent(jLabelC))
                                .addGap(0, 445, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTextFieldC)
                                    .addComponent(jTextFieldB)
                                    .addComponent(jTextFieldA))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonA, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButtonB, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButtonC, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addComponent(jLabelState, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jProgressBarA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jProgressBarB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jProgressBarC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelA)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonA))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jProgressBarA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jProgressBarB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelC)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonC))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jProgressBarC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelD)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonD))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jProgressBarD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelState)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FileServerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FileServerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FileServerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FileServerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                // Instanciamos la interfaz (el JFrame)
                FileServerUI ui = new FileServerUI();
                
                // Creamos un FileServer
                FileServer fs = null;
                
                try {
                    fs = new FileServer(3000);
                    
                    // Llenamos el diccionario de archivos disponibles
                    // con las llaves A, B, C y D y archivos con UI asociada
                    // observe que FileUI interactua con esta interfaz
                    fs.setFile("A", new FileUI("A", ui.jButtonA,
                        ui.jTextFieldA, ui.jLabelA, ui.jProgressBarA));
                    fs.setFile("B", new FileUI("B", ui.jButtonB,
                        ui.jTextFieldB, ui.jLabelB, ui.jProgressBarB));
                    // TODO: completa C y D
                } catch (IOException ex) {
                    Logger.getLogger(FileServerUI.class.getName()).log(Level.SEVERE, null, ex);
                }
                
                if (fs != null) {
                    // Comenzamos el servidor de archivos en un hilo independiente
                    // para que no bloquee la interfaz
                    // TODO: Inicia en un hilo a `fs`
                    // Hint: usa el método start()
                }
                
                // Mostramos la interfaz
                ui.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButtonA;
    public javax.swing.JButton jButtonB;
    public javax.swing.JButton jButtonC;
    public javax.swing.JButton jButtonD;
    public javax.swing.JLabel jLabelA;
    public javax.swing.JLabel jLabelB;
    public javax.swing.JLabel jLabelC;
    public javax.swing.JLabel jLabelD;
    public javax.swing.JLabel jLabelState;
    public javax.swing.JProgressBar jProgressBarA;
    public javax.swing.JProgressBar jProgressBarB;
    public javax.swing.JProgressBar jProgressBarC;
    public javax.swing.JProgressBar jProgressBarD;
    public javax.swing.JTextField jTextFieldA;
    public javax.swing.JTextField jTextFieldB;
    public javax.swing.JTextField jTextFieldC;
    public javax.swing.JTextField jTextFieldD;
    // End of variables declaration//GEN-END:variables
}
