/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package miprograma;

import java.awt.List;
import java.util.ArrayList;

/**
 *
 * @author Aula E5
 */
public class App extends javax.swing.JFrame {

    ArrayList<Contacto> contactos;
    List memoria;
    int mid;
    int eid;
    
    /**
     * Creates new form App
     */
    public App() {
        initComponents();
        
        this.contactos = new ArrayList();
        
        this.mid = 0;
        this.eid = 0;
        this.memoria = new List();
        
        this.mostrar_menu();
    }
    
    void mostrar_menu() {
        this.mid = 0;
        
        String texto_menu = String.format(
            "Selecciona una opción%n" +
            "   1. Buscar contacto%n" +
            "   2. Agregar contacto%n" +
            "   3. Modificar contacto%n" +
            "   4. Eliminar contacto%n"
        );
        
        this.jTextArea1.setText(texto_menu);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Monospaced", 0, 24)); // NOI18N
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jButton1.setText("aceptar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 548, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextField1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (mid == 0) { // Mostrar Menú
            String input = this.jTextField1.getText();
        
            int op = 0;

            try {
                op = Integer.parseInt(input);
            } catch(Exception e) {
                // TODO: Mostrar una alerta al usuario
            }

            if (op == 2) {
                this.agregar_contacto(0);
            }
        } else if (mid == 1) { // Agregar Contacto
            if (eid == 0) {
                String nombre = this.jTextField1.getText();
                this.memoria.add(nombre);
                this.agregar_contacto(1);
            } else if (this.eid == 1) {
                String telefono = this.jTextField1.getText();
                this.memoria.add(telefono);
                this.agregar_contacto(2);
            } else if (this.eid == 2) {
                this.mostrar_menu();
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    void agregar_contacto(int estado) {
        this.mid = 1;
        this.eid = estado;
        if (estado == 0) {
            this.jTextArea1.setText("Ingresa el nombre");
        } else if (estado == 1) {
            this.jTextArea1.setText("Ingresa el telefono");
        } else {
            String nombre = (String)this.memoria.getItem(0);
            String telefono = (String)this.memoria.getItem(1);
            
            Contacto c = new Contacto(nombre, telefono);
            
            this.contactos.add(c);
            
            this.jTextArea1.setText("Se agregó el contacto: " + c.descripcion());
            
            this.memoria.clear();
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new App().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
